In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
import seaborn as sns

In [4]:
import matplotlib.pyplot as plt

# load dataset

In [5]:
file = pd.read_csv("loan.csv")

In [6]:
file.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001003,Male,Yes,1,Graduate,No,4583.0,1508.0,128.0,360.0,1.0,Rural,N
1,LP001005,Male,Yes,0,Graduate,Yes,3000.0,0.0,66.0,360.0,1.0,Urban,Y
2,LP001006,Male,Yes,0,Not Graduate,No,2583.0,2358.0,120.0,360.0,1.0,Urban,Y
3,LP001008,Male,No,0,Graduate,No,6000.0,0.0,141.0,360.0,1.0,Urban,Y
4,LP001013,Male,Yes,0,Not Graduate,No,2333.0,1516.0,95.0,360.0,1.0,Urban,Y

In [86]:
file.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 381 entries, 0 to 380
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            381 non-null    object
 1   Gender             376 non-null    object
 2   Married            381 non-null    object
 3   Dependents         373 non-null    object
 4   Education          377 non-null    object
 5   Self_Employed      358 non-null    object
 6   ApplicantIncome    377 non-null    float64
 7   CoapplicantIncome  376 non-null    float64
 8   LoanAmount         379 non-null    float64
 9   Loan_Amount_Term   368 non-null    float64
 10  Credit_History     351 non-null    float64
 11  Property_Area      380 non-null    object
 12  Loan_Status        381 non-null    object
dtypes: float64(5), object(8)
memory usage: 38.8+ KB

# missing value check

In [7]:
file.isna().sum()

Loan_ID               0
Gender                5
Married               0
Dependents            8
Education             4
Self_Employed        23
ApplicantIncome       4
CoapplicantIncome     5
LoanAmount            2
Loan_Amount_Term     13
Credit_History       30
Property_Area         1
Loan_Status           0
dtype: int64

# check duplicate value

In [12]:
file.duplicated().sum()

0

In [13]:
file.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [ ]:
x = file.drop(columns=["Loan_Status","Loan_ID"],axis=1)

In [15]:
y = file["Loan_Status"]

In [16]:
y = y.map({"N":0,"Y":1})

In [18]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer,make_column_selector
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,classification_report,recall_score,confusion_matrix

In [19]:
x_train,x_test , y_train,y_test=train_test_split(x,y, test_size=0.2,random_state=42)

In [23]:
num_colums = Pipeline([
    ("num",SimpleImputer(strategy="median")),
    ("scaling",StandardScaler())
])
cat_colums = Pipeline([
    ("cat",SimpleImputer(strategy="most_frequent")),
    ("encoding",OneHotEncoder(handle_unknown="ignore",sparse=False))
])

In [24]:
transformer = ColumnTransformer([
    ("num_column",num_colums,make_column_selector(dtype_include=np.number)),
     ("cat_column",cat_colums,make_column_selector(dtype_include="object"))
])

In [25]:
model_pipeline = Pipeline([
    ("preprocessing",transformer),
    ("model",LogisticRegression())
])

In [26]:
model_pipeline

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num_column',
                                                  Pipeline(steps=[('num',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaling',
                                                                   StandardScaler())]),
                                                  <sklearn.compose._column_transformer.make_column_selector object at 0x000001D7FE1D35B0>),
                                                 ('cat_column',
                                                  Pipeline(steps=[('cat',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoding',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse=False))]),
                                                  <sklearn.compose._column_transformer.make_column_selector object at 0x000001D7FE1D38B0>)])),
                ('model', LogisticRegression())])

In [27]:
model_pipeline.fit(x_train,y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num_column',
                                                  Pipeline(steps=[('num',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaling',
                                                                   StandardScaler())]),
                                                  <sklearn.compose._column_transformer.make_column_selector object at 0x000001D7FE1D35B0>),
                                                 ('cat_column',
                                                  Pipeline(steps=[('cat',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoding',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse=False))]),
                                                  <sklearn.compose._column_transformer.make_column_selector object at 0x000001D7FE1D38B0>)])),
                ('model', LogisticRegression())])

# training data predict

In [28]:
y_predict_train = model_pipeline.predict(x_train)

In [29]:
y_predict_train

array([1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0], dtype=int64)

# actual and predict value1

In [30]:
pd.DataFrame({
    "actual":y_train,
    "predicted value":y_predict_train
})

     actual  predicted value
78        1                1
265       1                1
93        0                0
377       1                1
272       1                1
..      ...              ...
71        1                1
106       1                1
270       1                1
348       1                1
102       0                0

[304 rows x 2 columns]

# testing data predicted

In [31]:
y_predict_test =model_pipeline.predict(x_test)

In [32]:
y_predict_test

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

# actual and predicted value

In [33]:
pd.DataFrame({
    "actual":y_test,
    "predicted":y_predict_test
})

     actual  predicted
266       1          1
192       1          1
46        1          1
55        0          1
57        1          1
..      ...        ...
165       1          1
63        1          1
249       1          1
280       1          1
357       0          1

[77 rows x 2 columns]

In [34]:
accuracy_score(y_test,y_predict_test)

0.8181818181818182

In [35]:
confusion_matrix(y_test,y_predict_test)

array([[ 7, 14],
       [ 0, 56]], dtype=int64)

In [108]:
file.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

# predicted fuction`

In [38]:
print(classification_report(y_train, y_predict_train))

              precision    recall  f1-score   support

           0       0.94      0.54      0.69        89
           1       0.84      0.99      0.91       215

    accuracy                           0.86       304
   macro avg       0.89      0.76      0.80       304
weighted avg       0.87      0.86      0.84       304

In [39]:
y.value_counts()

1    271
0    110
Name: Loan_Status, dtype: int64

In [45]:
Y_data = file[(file.Loan_Status=="Y")].sample(110)

In [46]:
N_data = file[(file.Loan_Status=="N")].sample(110)

In [49]:
new_data = pd.concat([Y_data,N_data]).sample(220)

In [50]:
new_data.Loan_Status.value_counts()

N    110
Y    110
Name: Loan_Status, dtype: int64

In [51]:
X = new_data.drop("Loan_Status",axis=1)
y = new_data.Loan_Status

In [53]:
x_train,x_test , y_train,y_test=train_test_split(X,y, test_size=0.2,random_state=42)

In [59]:
model_pipeline.fit(X,y)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num_column',
                                                  Pipeline(steps=[('num',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaling',
                                                                   StandardScaler())]),
                                                  <sklearn.compose._column_transformer.make_column_selector object at 0x000001D7FE1D35B0>),
                                                 ('cat_column',
                                                  Pipeline(steps=[('cat',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoding',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse=False))]),
                                                  <sklearn.compose._column_transformer.make_column_selector object at 0x000001D7FE1D38B0>)])),
                ('model', LogisticRegression())])

In [60]:
y_predict_train = model_pipeline.predict(X)

In [61]:
print(classification_report(y,y_predict_train))

              precision    recall  f1-score   support

           N       0.97      0.80      0.88       110
           Y       0.83      0.97      0.90       110

    accuracy                           0.89       220
   macro avg       0.90      0.89      0.89       220
weighted avg       0.90      0.89      0.89       220

In [58]:
y_train.value_counts()

Y    91
N    85
Name: Loan_Status, dtype: int64

# using Smote For Class Imbalacing

In [65]:
data = pd.read_csv("loan.csv")

In [67]:
X = data.drop("Loan_Status",axis=1)
y = data.Loan_Status

In [68]:

y = y.map({"N":0,"Y":1})

In [63]:
!pip install imblearn

Collecting imblearn
  Downloading imblearn-0.0-py2.py3-none-any.whl (1.9 kB)
Collecting imbalanced-learn
  Downloading imbalanced_learn-0.12.4-py3-none-any.whl (258 kB)
     ------------------------------------ 258.3/258.3 kB 587.9 kB/s eta 0:00:00
Requirement already satisfied: scipy>=1.5.0 in c:\programdata\anaconda3\lib\site-packages (from imbalanced-learn->imblearn) (1.9.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\programdata\anaconda3\lib\site-packages (from imbalanced-learn->imblearn) (2.2.0)
Requirement already satisfied: numpy>=1.17.3 in c:\programdata\anaconda3\lib\site-packages (from imbalanced-learn->imblearn) (1.21.5)
Collecting joblib>=1.1.1
  Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
     -------------------------------------- 309.1/309.1 kB 1.9 MB/s eta 0:00:00
Requirement already satisfied: scikit-learn>=1.0.2 in c:\programdata\anaconda3\lib\site-packages (from imbalanced-learn->imblearn) (1.0.2)
Installing collected packages: joblib, imbalanced-learn, imblearn
  Attempting uninstall: joblib
    Found existing installation: joblib 1.1.0
    Uninstalling joblib-1.1.0:
      Successfully uninstalled joblib-1.1.0
Successfully installed imbalanced-learn-0.12.4 imblearn-0.0 joblib-1.5.3

In [72]:
X.drop("Loan_ID",axis=1,inplace=True)

ValueError: could not convert string to float: 'Male'